# Generated by Django 3.2.16 on 2023-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0002_destination_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=0, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
